version: 2
jobs:
  build:
    docker: 
      - image: davidva/unibuild-32	
    parallelism: 1
    steps:
      - run: docker run --privileged=true --cap-add=SYS_ADMIN -v $(pwd)/32:/root/enjoy/ --security-opt seccomp:unconfined davidva/unibuild-32 /bin/sh -c "rm -f /urpms && wget -c https://raw.githubusercontent.com/kuboosoft/united-build/master/urpms && chmod a+x urpms && /urpms -g UnitedRPMs/blender -s blender.spec -r true -d 'dist .fc32' -u true" 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: https://webhooks.gitter.im/e/8ff0b35066468a87de71

        


